package com.spring.restful.users.app.common;

public interface DbQueries {
	String INSERT_USER="INSERT INTO USER1 (ID, NAME, PASSWORD,CREATEDATE,LASTLOGIN) VALUES (USER_SEQ_ID.NEXTVAL,?, ?,?,?)";
	String GET_ALL_USERS="SELECT ID,NAME,PASSWORD,CREATEDATE,LASTLOGIN FROM USER1";
	String GET_USER_BY_ID="SELECT ID,NAME,PASSWORD,CREATEDATE,LASTLOGIN FROM USER1 WHERE ID=?";
	String UPDATE_USER_BY_ID="UPDATE USER1  SET NAME =?, PASSWORD =?, LASTLOGIN =? WHERE  ID =?";
	String DELETE_USER_BY_ID="DELETE FROM USER1 WHERE ID =?";


}
